set_property PACKAGE_PIN V10 [get_ports {o_seg_1_0[6]}]
set_property PACKAGE_PIN W11 [get_ports {o_seg_1_0[5]}]
set_property PACKAGE_PIN W12 [get_ports {o_seg_1_0[4]}]
set_property PACKAGE_PIN AA9 [get_ports {o_seg_1_0[3]}]
set_property PACKAGE_PIN Y10 [get_ports {o_seg_1_0[2]}]
set_property PACKAGE_PIN AA11 [get_ports {o_seg_1_0[1]}]
set_property PACKAGE_PIN Y11 [get_ports {o_seg_1_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg_1_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg_1_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg_1_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg_1_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg_1_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg_1_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg_1_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_buttom_add_0]
set_property IOSTANDARD LVCMOS33 [get_ports i_buttom_clr_0]
set_property IOSTANDARD LVCMOS33 [get_ports i_buttom_mis_0]
set_property PACKAGE_PIN T18 [get_ports i_buttom_add_0]
set_property PACKAGE_PIN P16 [get_ports i_buttom_clr_0]
set_property PACKAGE_PIN R16 [get_ports i_buttom_mis_0]



set_property PACKAGE_PIN W8 [get_ports o_seg_sel]
set_property IOSTANDARD LVCMOS33 [get_ports o_seg_sel]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
